int main() {
	int a, res, n;
    n = getint();
    int i = 0;
    while (i < n){
        res = 0;
        a = getint();
        if (a > 0 && a < 100)
            if (a > 0 && a < 99)
                if (a > 0 && a < 98)
                    if (a > 0 && a < 97)
                        if (a > 0 && a < 96)
                            if (a > 0 && a < 95)
                                if (a > 0 && a < 94)
                                    if (a > 0 && a < 93)
                                        if (a > 0 && a < 92)
                                            if (a > 0 && a < 91)
                                                if (a > 0 && a < 90)
                                                    if (a > 0 && a < 89)
                                                        if (a > 0 && a < 88)
                                                            if (a > 0 && a < 87)
                                                                if (a > 0 && a < 86)
                                                                    if (a > 0 && a < 85)
                                                                        if (a > 0 && a < 84)
                                                                            if (a > 0 && a < 83)
                                                                                if (a > 0 && a < 82)
                                                                                    if (a > 0 && a < 81)
                                                                                        if (a > 0 && a < 80)
                                                                                            if (a > 0 && a < 79)
                                                                                                if (a > 0 && a < 78)
                                                                                                    if (a > 0 && a < 77)
                                                                                                        if (a > 0 && a < 76)
                                                                                                            if (a > 0 && a < 75)
                                                                                                                if (a > 0 && a < 74)
                                                                                                                    if (a > 0 && a < 73)
                                                                                                                        if (a > 0 && a < 72)
                                                                                                                            if (a > 0 && a < 71)
                                                                                                                                if (a > 0 && a < 70)
                                                                                                                                    if (a > 0 && a < 69)
                                                                                                                                        if (a > 0 && a < 68)
                                                                                                                                            if (a > 0 && a < 67)
                                                                                                                                                if (a > 0 && a < 66)
                                                                                                                                                    if (a > 0 && a < 65)
                                                                                                                                                        if (a > 0 && a < 64)
                                                                                                                                                            if (a > 0 && a < 63)
                                                                                                                                                                if (a > 0 && a < 62)
                                                                                                                                                                    if (a > 0 && a < 61)
                                                                                                                                                                        if (a > 0 && a < 60)
                                                                                                                                                                            if (a > 0 && a < 59)
                                                                                                                                                                                if (a > 0 && a < 58)
                                                                                                                                                                                    if (a > 0 && a < 57)
                                                                                                                                                                                        if (a > 0 && a < 56)
                                                                                                                                                                                            if (a > 0 && a < 55)
                                                                                                                                                                                                if (a > 0 && a < 54)
                                                                                                                                                                                                    if (a > 0 && a < 53)
                                                                                                                                                                                                        if (a > 0 && a < 52)
                                                                                                                                                                                                            if (a > 0 && a < 51)
                                                                                                                                                                                                                if (a > 0 && a < 50)
                                                                                                                                                                                                                    if (a > 0 && a < 49)
                                                                                                                                                                                                                        if (a > 0 && a < 48)
                                                                                                                                                                                                                            if (a > 0 && a < 47)
                                                                                                                                                                                                                                if (a > 0 && a < 46)
                                                                                                                                                                                                                                    if (a > 0 && a < 45)
                                                                                                                                                                                                                                        if (a > 0 && a < 44)
                                                                                                                                                                                                                                            if (a > 0 && a < 43)
                                                                                                                                                                                                                                                if (a > 0 && a < 42)
                                                                                                                                                                                                                                                    if (a > 0 && a < 41)
                                                                                                                                                                                                                                                        if (a > 0 && a < 40)
                                                                                                                                                                                                                                                            if (a > 0 && a < 39)
                                                                                                                                                                                                                                                                if (a > 0 && a < 38)
                                                                                                                                                                                                                                                                    if (a > 0 && a < 37)
                                                                                                                                                                                                                                                                        if (a > 0 && a < 36)
                                                                                                                                                                                                                                                                            if (a > 0 && a < 35)
                                                                                                                                                                                                                                                                                if (a > 0 && a < 34)
                                                                                                                                                                                                                                                                                    if (a > 0 && a < 33)
                                                                                                                                                                                                                                                                                        if (a > 0 && a < 32)
                                                                                                                                                                                                                                                                                            if (a > 0 && a < 31)
                                                                                                                                                                                                                                                                                                if (a > 0 && a < 30)
                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 29)
                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 28)
                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 27)
                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 26)
                                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 25)
                                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 24)
                                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 23)
                                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 22)
                                                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 21)
                                                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 20)
                                                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 19)
                                                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 18)
                                                                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 17)
                                                                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 16)
                                                                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 15)
                                                                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 14)
                                                                                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 13)
                                                                                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 12)
                                                                                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 11)
                                                                                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 10)
                                                                                                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 9)
                                                                                                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 8)
                                                                                                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 7)
                                                                                                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 6)
                                                                                                                                                                                                                                                                                                                                                                                                    if (a > 0 && a < 5)
                                                                                                                                                                                                                                                                                                                                                                                                        if (a > 0 && a < 4)
                                                                                                                                                                                                                                                                                                                                                                                                            if (a > 0 && a < 3)
                                                                                                                                                                                                                                                                                                                                                                                                                if (a > 0 && a < 2)
                                                                                                                                                                                                                                                                                                                                                                                                                    res = res + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                else res = res + 2;
                                                                                                                                                                                                                                                                                                                                                                                                            else res = res + 3;
                                                                                                                                                                                                                                                                                                                                                                                                        else res = res + 4;
                                                                                                                                                                                                                                                                                                                                                                                                    else res = res + 5;
                                                                                                                                                                                                                                                                                                                                                                                                else res = res + 6;
                                                                                                                                                                                                                                                                                                                                                                                            else res = res + 7;
                                                                                                                                                                                                                                                                                                                                                                                        else res = res + 8;
                                                                                                                                                                                                                                                                                                                                                                                    else res = res + 9;
                                                                                                                                                                                                                                                                                                                                                                                else res = res + 10;
                                                                                                                                                                                                                                                                                                                                                                            else res = res + 11;
                                                                                                                                                                                                                                                                                                                                                                        else res = res + 12;
                                                                                                                                                                                                                                                                                                                                                                    else res = res + 13;
                                                                                                                                                                                                                                                                                                                                                                else res = res + 14;
                                                                                                                                                                                                                                                                                                                                                            else res = res + 15;
                                                                                                                                                                                                                                                                                                                                                        else res = res + 16;
                                                                                                                                                                                                                                                                                                                                                    else res = res + 17;
                                                                                                                                                                                                                                                                                                                                                else res = res + 18;
                                                                                                                                                                                                                                                                                                                                            else res = res + 19;
                                                                                                                                                                                                                                                                                                                                        else res = res + 20;
                                                                                                                                                                                                                                                                                                                                    else res = res + 21;
                                                                                                                                                                                                                                                                                                                                else res = res + 22;
                                                                                                                                                                                                                                                                                                                            else res = res + 23;
                                                                                                                                                                                                                                                                                                                        else res = res + 24;
                                                                                                                                                                                                                                                                                                                    else res = res + 25;
                                                                                                                                                                                                                                                                                                                else res = res + 26;
                                                                                                                                                                                                                                                                                                            else res = res + 27;
                                                                                                                                                                                                                                                                                                        else res = res + 28;
                                                                                                                                                                                                                                                                                                    else res = res + 29;
                                                                                                                                                                                                                                                                                                else res = res + 30;
                                                                                                                                                                                                                                                                                            else res = res + 31;
                                                                                                                                                                                                                                                                                        else res = res + 32;
                                                                                                                                                                                                                                                                                    else res = res + 33;
                                                                                                                                                                                                                                                                                else res = res + 34;
                                                                                                                                                                                                                                                                            else res = res + 35;
                                                                                                                                                                                                                                                                        else res = res + 36;
                                                                                                                                                                                                                                                                    else res = res + 37;
                                                                                                                                                                                                                                                                else res = res + 38;
                                                                                                                                                                                                                                                            else res = res + 39;
                                                                                                                                                                                                                                                        else res = res + 40;
                                                                                                                                                                                                                                                    else res = res + 41;
                                                                                                                                                                                                                                                else res = res + 42;
                                                                                                                                                                                                                                            else res = res + 43;
                                                                                                                                                                                                                                        else res = res + 44;
                                                                                                                                                                                                                                    else res = res + 45;
                                                                                                                                                                                                                                else res = res + 46;
                                                                                                                                                                                                                            else res = res + 47;
                                                                                                                                                                                                                        else res = res + 48;
                                                                                                                                                                                                                    else res = res + 49;
                                                                                                                                                                                                                else res = res + 50;
                                                                                                                                                                                                            else res = res + 51;
                                                                                                                                                                                                        else res = res + 52;
                                                                                                                                                                                                    else res = res + 53;
                                                                                                                                                                                                else res = res + 54;
                                                                                                                                                                                            else res = res + 55;
                                                                                                                                                                                        else res = res + 56;
                                                                                                                                                                                    else res = res + 57;
                                                                                                                                                                                else res = res + 58;
                                                                                                                                                                            else res = res + 59;
                                                                                                                                                                        else res = res + 60;
                                                                                                                                                                    else res = res + 61;
                                                                                                                                                                else res = res + 62;
                                                                                                                                                            else res = res + 63;
                                                                                                                                                        else res = res + 64;
                                                                                                                                                    else res = res + 65;
                                                                                                                                                else res = res + 66;
                                                                                                                                            else res = res + 67;
                                                                                                                                        else res = res + 68;
                                                                                                                                    else res = res + 69;
                                                                                                                                else res = res + 70;
                                                                                                                            else res = res + 71;
                                                                                                                        else res = res + 72;
                                                                                                                    else res = res + 73;
                                                                                                                else res = res + 74;
                                                                                                            else res = res + 75;
                                                                                                        else res = res + 76;
                                                                                                    else res = res + 77;
                                                                                                else res = res + 78;
                                                                                            else res = res + 79;
                                                                                        else res = res + 80;
                                                                                    else res = res + 81;
                                                                                else res = res + 82;
                                                                            else res = res + 83;
                                                                        else res = res + 84;
                                                                    else res = res + 85;
                                                                else res = res + 86;
                                                            else res = res + 87;
                                                        else res = res + 88;
                                                    else res = res + 89;
                                                else res = res + 90;
                                            else res = res + 91;
                                        else res = res + 92;
                                    else res = res + 93;
                                else res = res + 94;
                            else res = res + 95;
                        else res = res + 96;
                    else res = res + 97;
                else res = res + 98;
            else res = res + 99;
        else res = res + 100;
        putint(res);
        putch(10);
        i = i + 1;
    }
	return 0;
}